(function(){'use strict';
var app=document.getElementById('app');
var state={lang:localStorage.getItem('dx_lang')||'ar',session:null};
var users=[
{id:'ADM-0001',role:'admin',name:'DawamX Administrator',email:'admin@dawamx.com',password:'admin123'},
{id:'0010',role:'employee',name:'محمد أحمد',email:'emp@dawamx.com',password:'0010'},
{id:'0011',role:'employee',name:'Ahmed Ali',email:'emp2@dawamx.com',password:'0011'}];
var T={ar:{sub:'نظام إدارة الموارد البشرية',id:'رقم الموظف / البريد الإلكتروني',pass:'كلمة المرور',enter:'دخول',bad:'بيانات الدخول غير صحيحة',logout:'تسجيل الخروج',dashboard:'لوحة التحكم',employees:'الموظفون',attendance:'الحضور',leaves:'الإجازات',payroll:'الرواتب',advances:'السلف',reports:'التقارير',menu:'القائمة',welcome:'مرحبًا',myDashboard:'لوحة تحكمي',myAttendance:'حضوري',myLeaves:'إجازاتي',mySalary:'راتبي',myAdvances:'سلفي',profile:'ملفي الشخصي'},en:{sub:'Human Resources Management',id:'Employee ID / Email',pass:'Password',enter:'Sign in',bad:'Invalid credentials',logout:'Logout',dashboard:'Dashboard',employees:'Employees',attendance:'Attendance',leaves:'Leaves',payroll:'Payroll',advances:'Advances',reports:'Reports',menu:'Menu',welcome:'Welcome',myDashboard:'My Dashboard',myAttendance:'My Attendance',myLeaves:'My Leaves',mySalary:'My Salary',myAdvances:'My Advances',profile:'My Profile'}};
function t(k){return T[state.lang][k]||k}
function applyLang(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr'}
function restore(){try{var r=sessionStorage.getItem('dx_session');state.session=r?JSON.parse(r):null}catch(e){state.session=null}}
function setLang(l){state.lang=l;localStorage.setItem('dx_lang',l);applyLang();state.session?renderApp():renderLogin()}
function route(){return (location.hash||'#dashboard').slice(1)||'dashboard'}
function renderLogin(){app.innerHTML='<main class="auth"><section class="auth-card"><div class="lang"><button data-lang="ar" class="'+(state.lang==='ar'?'active':'')+'">عربي</button><button data-lang="en" class="'+(state.lang==='en'?'active':'')+'">English</button></div><div class="brand">Dawam<span>X</span></div><div class="subtitle">'+t('sub')+'</div><form id="loginForm"><div class="field"><label>'+t('id')+'</label><input id="loginId" autocomplete="username" autofocus></div><div class="field"><label>'+t('pass')+'</label><input id="loginPassword" type="password" autocomplete="current-password"></div><button class="btn btn-primary" type="submit">'+t('enter')+'</button><div id="loginError" class="error"></div></form><div class="demo">Admin: <b>admin@dawamx.com</b> / <b>admin123</b><br>Employee: <b>0010</b> / <b>0010</b></div></section></main>';
app.querySelectorAll('[data-lang]').forEach(function(b){b.onclick=function(){setLang(this.dataset.lang)}});
app.querySelector('#loginForm').onsubmit=function(e){e.preventDefault();var id=app.querySelector('#loginId').value.trim(),pw=app.querySelector('#loginPassword').value,u=users.find(function(x){return(x.id===id||x.email===id)&&x.password===pw});if(!u){app.querySelector('#loginError').textContent=t('bad');return}state.session={id:u.id,role:u.role,name:u.name,email:u.email};sessionStorage.setItem('dx_session',JSON.stringify(state.session));location.hash='dashboard';renderApp()}}
function items(){return state.session.role==='admin'?[['dashboard','🏠',t('dashboard')],['employees','👥',t('employees')],['attendance','🕐',t('attendance')],['leaves','📅',t('leaves')],['payroll','💰',t('payroll')],['advances','💳',t('advances')],['reports','📊',t('reports')]]:[['dashboard','🏠',t('myDashboard')],['my-attendance','🕐',t('myAttendance')],['my-leaves','📅',t('myLeaves')],['my-salary','💰',t('mySalary')],['my-advances','💳',t('myAdvances')],['profile','👤',t('profile')]]}
function renderApp(){var nav=items().map(function(x){return'<button data-route="'+x[0]+'">'+x[1]+' '+x[2]+'</button>'}).join('');app.innerHTML='<div id="overlay" class="overlay"></div><div class="shell"><aside id="sidebar" class="sidebar"><div class="side-brand">Dawam<span>X</span></div><nav class="nav">'+nav+'<button id="logoutBtn" class="logout">🚪 '+t('logout')+'</button></nav></aside><main class="main"><div class="topbar"><button id="menuBtn" class="btn mobile-menu">☰ '+t('menu')+'</button><div class="top-actions"><div class="user-pill">'+state.session.name+' · '+state.session.id+'</div><button id="langBtn" class="btn">'+(state.lang==='ar'?'English':'عربي')+'</button></div></div><section id="page"></section></main></div>';app.querySelectorAll('[data-route]').forEach(function(b){b.onclick=function(){location.hash=this.dataset.route;closeMenu();renderPage()}});app.querySelector('#logoutBtn').onclick=function(){state.session=null;sessionStorage.removeItem('dx_session');location.hash='';renderLogin()};app.querySelector('#langBtn').onclick=function(){setLang(state.lang==='ar'?'en':'ar')};app.querySelector('#menuBtn').onclick=openMenu;app.querySelector('#overlay').onclick=closeMenu;renderPage()}
function renderPage(){var p=app.querySelector('#page'),r=route(),admin=state.session.role==='admin';if(r==='dashboard'){p.innerHTML='<h1>'+t('welcome')+'، '+state.session.name+'</h1><p class="text-muted">DawamX HR Platform</p><div class="grid">'+(admin?'<article class="card">Employees<div class="stat">128</div></article><article class="card">Present Today<div class="stat">116</div></article><article class="card">Pending Leaves<div class="stat">7</div></article><article class="card">Pending Advances<div class="stat">4</div></article>':'<article class="card">'+t('myAttendance')+'<div class="stat">—</div></article><article class="card">'+t('myLeaves')+'<div class="stat">—</div></article>')+'</div>'}else p.innerHTML='<article class="card"><h2>'+r+'</h2><p class="text-muted">Module foundation will be built after core confirmation.</p></article>'}
function openMenu(){app.querySelector('#sidebar').classList.add('open');app.querySelector('#overlay').classList.add('show')}
function closeMenu(){app.querySelector('#sidebar').classList.remove('open');app.querySelector('#overlay').classList.remove('show')}
function fatal(e){app.innerHTML='<main class="error-screen"><div class="error-box"><h1>DawamX Startup Error</h1><p>تم منع الصفحة البيضاء الصامتة.</p><b>'+String(e.message||e)+'</b></div></main>';console.error(e)}
window.onhashchange=function(){if(state.session)renderPage()};
try{applyLang();restore();state.session?renderApp():renderLogin()}catch(e){fatal(e)}
})();