import {state,setLanguage,setSession,clearSession} from '../core/state.js';
import {t} from '../i18n/i18n.js';
import {authenticate} from '../auth/auth.js';
import {go,renderRoute,registerRoute} from '../core/router.js';
const app=()=>document.getElementById('app');
function navItems(){const l=state.lang;return state.session.role==='admin'?[['dashboard','🏠',t(l,'dashboard')],['employees','👥',t(l,'employees')],['attendance','🕐',t(l,'attendance')],['leaves','📅',t(l,'leaves')],['payroll','💰',t(l,'payroll')],['advances','💳',t(l,'advances')],['reports','📊',t(l,'reports')]]:[['dashboard','🏠',t(l,'myDashboard')],['my-attendance','🕐',t(l,'myAttendance')],['my-leaves','📅',t(l,'myLeaves')],['my-salary','💰',t(l,'mySalary')],['my-advances','💳',t(l,'myAdvances')],['profile','👤',t(l,'profile')]]}
export function renderLogin(){const l=state.lang;app().innerHTML=`<main class="auth"><section class="auth-card"><div class="lang"><button data-lang="ar" class="${l==='ar'?'active':''}">عربي</button><button data-lang="en" class="${l==='en'?'active':''}">English</button></div><div class="brand">Dawam<span>X</span></div><div class="subtitle">${t(l,'sub')}</div><form id="loginForm"><div class="field"><label>${t(l,'id')}</label><input id="loginId" autocomplete="username" autofocus></div><div class="field"><label>${t(l,'pass')}</label><input id="loginPassword" type="password" autocomplete="current-password"></div><button class="btn btn-primary" type="submit">${t(l,'enter')}</button><div id="loginError" class="error"></div></form><div class="demo">Admin: <b>admin@dawamx.com</b> / <b>admin123</b><br>Employee: <b>0010</b> / <b>0010</b></div></section></main>`;
app().querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>{setLanguage(btn.dataset.lang);renderLogin()}));
app().querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();const id=app().querySelector('#loginId').value.trim();const pw=app().querySelector('#loginPassword').value;const user=authenticate(id,pw);if(!user){app().querySelector('#loginError').textContent=t(l,'bad');return}const {password,...safeUser}=user;setSession(safeUser);renderApp();go('dashboard')})}
export function renderApp(){const l=state.lang;const items=navItems();app().innerHTML=`<div id="overlay" class="overlay"></div><div class="shell"><aside id="sidebar" class="sidebar"><div class="side-brand">Dawam<span>X</span></div><nav class="nav">${items.map(([route,icon,label])=>`<button data-route="${route}">${icon} ${label}</button>`).join('')}<button class="logout" id="logoutBtn">🚪 ${t(l,'logout')}</button></nav></aside><main class="main"><div class="topbar"><button class="btn mobile-menu" id="menuBtn">☰ ${t(l,'menu')}</button><div class="top-actions"><div class="user-pill">${state.session.name} · ${state.session.id}</div><button class="btn" id="langToggle">${l==='ar'?'English':'عربي'}</button></div></div><section id="page" class="page"></section></main></div>`;
app().querySelectorAll('[data-route]').forEach(btn=>btn.addEventListener('click',()=>{closeMenu();go(btn.dataset.route)}));
app().querySelector('#logoutBtn').addEventListener('click',()=>{clearSession();history.replaceState(null,'',location.pathname);renderLogin()});
app().querySelector('#langToggle').addEventListener('click',()=>{setLanguage(state.lang==='ar'?'en':'ar');renderApp()});
app().querySelector('#menuBtn').addEventListener('click',openMenu);app().querySelector('#overlay').addEventListener('click',closeMenu);renderRoute(app().querySelector('#page'))}
function openMenu(){app().querySelector('#sidebar')?.classList.add('open');app().querySelector('#overlay')?.classList.add('show')}function closeMenu(){app().querySelector('#sidebar')?.classList.remove('open');app().querySelector('#overlay')?.classList.remove('show')}
registerRoute('dashboard',page=>{const l=state.lang;const admin=state.session.role==='admin';page.innerHTML=`<div class="page-head"><div><h1>${t(l,'welcome')}، ${state.session.name}</h1><p class="text-muted">DawamX HR Platform</p></div></div><div class="grid">${admin?`<article class="card">${t(l,'employeesCount')}<div class="stat">128</div></article><article class="card">${t(l,'present')}<div class="stat">116</div></article><article class="card">${t(l,'pendingLeaves')}<div class="stat">7</div></article><article class="card">${t(l,'pendingAdvances')}<div class="stat">4</div></article>`:`<article class="card">${t(l,'myAttendance')}<div class="stat">—</div></article><article class="card">${t(l,'myLeaves')}<div class="stat">—</div></article>`}</div>`});
['employees','attendance','leaves','payroll','advances','reports','my-attendance','my-leaves','my-salary','my-advances','profile'].forEach(route=>registerRoute(route,page=>{page.innerHTML=`<div class="card"><h2>${route}</h2><p class="text-muted">Module foundation will be implemented after core confirmation.</p></div>`}));
